- name: Install Ansible dependencies
  zypper:
    name: [ "python3-psycopg2", "sudo" ]

- name: Install postgresql packages
  zypper:
    name: [ 'postgresql-server', 'postgresql' ]

- name: Enable and run postgresql
  systemd:
    name: postgresql
    enabled: yes
    state: started

- name: Create database
  become: yes
  become_user: postgres
  postgresql_db:
    name: "{{ postgresql.databasename | default('prosody') }}"

- name: Create database user
  become: yes
  become_user: postgres
  postgresql_user:
    db: "{{ postgresql.databasename | default('prosody') }}"
    name: "{{ postgresql.username | default('prosody') }}"
    password: "{{ pgpwd }}"
    priv: ALL
    role_attr_flags: NOSUPERUSER,NOCREATEDB

- name: Enable password authentication for localhost
  blockinfile:
    path: "/var/lib/pgsql/data/pg_hba.conf"
    insertafter: "^#\\s+TYPE\\s+DATABASE\\s+USER\\s+ADDRESS\\s+METHOD"
    block: |
      host    {{ postgresql.databasename | default('prosody') }}         {{ postgresql.username | default('prosody') }}         127.0.0.1/32            password
      host    {{ postgresql.databasename | default('prosody') }}         {{ postgresql.username | default('prosody') }}         ::1/128                 password
  notify: restart postgresql
