- name: Install Ansible dependencies
  zypper:
    name: "python3-psycopg2"

- name: Install postgresql packages
  zypper:
    pkg: [ 'postgresql-server', 'postgresql', 'sudo' ]
  notify: enable postgresql

- name: Enable and run postgresql
  systemd:
    name: postgresql
    enabled: yes
    state: started

- name: Create database
  become: yes
  become_user: postgres
  become_method: sudo
  postgresql_db:
    name: "{{ postgresql.databasename | default('prosody') }}"

- name: Create database user
  become: yes
  become_user: postgres
  become_method: sudo
  postgresql_user:
    name: "{{ postgresql.username | default('prosody') }}"
    password: "{{ pgpwd }}"
    expires: "infinity"

- name: Give database user access to database
  become: yes
  become_user: postgres
  become_method: sudo
  postgresql_privs:
    db: "{{ postgresql.databasename | default('prosody') }}"
    role: "{{ postgresql.username | default('prosody') }}"
    privs: ALL
    type: database
