# Install Apache2
- name: Install Apache2
  zypper:
    name: "apache2"

- name: Install Apache2-Mod-PHP
  zypper:
    name: "apache2-mod_php7"
  notify: restart apache2

- name: Enable required Apache2 modules
  apache2_module:
    name: "{{ item }}"
  loop:
    - "rewrite"
    - "headers"
    - "proxy"
    - "proxy_http"
    - "proxy_wstunnel"
    - "php7"
  notify: restart apache2

- name: Enable Apache2
  systemd:
    name: apache2
    enabled: yes


# Set up Apache2 configuration
- name: Create TLS configuration
  template:
    src: "letsencrypt-ssl-apache.j2"
    dest: "/etc/apache2/letsencrypt-ssl-apache.conf"
    mode: "0644"
  notify: restart apache2

- name: Enable SSL server flag
  lineinfile:
    path: "/etc/sysconfig/apache2"
    regexp: '^APACHE_SERVER_FLAGS='
    line:  'APACHE_SERVER_FLAGS="SSL"'
  notify: restart apache2

- name: Explicitly set HTTP servername
  template:
    src: "servername.j2"
    dest: "/etc/apache2/vhosts.d/01-set-servername.conf"
    mode: "0644"
  notify: restart apache2

- name: Create common web vHost configuration
  template:
    src: "vhost-web.j2"
    dest: "/etc/apache2/vhosts.d/{{ prosody.web_domain.name | default(inventory_hostname) }}.conf"
    mode: "0644"
  notify: restart apache2

- name: Create vHost configurations for XMPP components
  include_tasks: vhosts.yml
  loop: "{{ prosody.xmpp_domains | map(attribute='components') }}"
  loop_control:
    loop_var: domain


# Install AnonIP
- name: Install dependencies for AnonIP
  zypper:
    name: ['git' ]

- name: Clone github repo for AnonIP
  git:
    repo: "https://github.com/DigitaleGesellschaft/Anonip.git"
    dest: "/usr/local/Anonip.git"
    clone: yes
    version: main
  notify: restart apache2
  tags:
    - skip_ansible_lint

- name: Mark AnonIP python script as executable
  file:
    dest: /usr/local/Anonip.git/anonip.py
    mode: "0755"


# Install main website's content
- name: Clone website content
  git:
    repo: "{{ prosody.web_domain.content_git.url }}"
    version: "{{ prosody.web_domain.content_git.branch | default('master') }}"
    dest: "/srv/var/www/vhosts/{{ prosody.web_domain.name | default(inventory_hostname) }}/"
    clone: yes
    update: yes
  tags:
    - skip_ansible_lint
  when: prosody.web_domain.content_git.url is defined and prosody.web_domain.content_git.branch is defined
