- name: Create vHost configurations for XMPP components
  template:
    src: "vhost-{{ item }}.j2"
    dest: "/etc/apache2/vhosts.d/{{ domain[item] }}.conf"
    mode: "0644"
  loop: "{{ domain | list }}"
  notify: restart apache2

- name: Create vHost directories
  file:
    path: "/srv/var/www/vhosts/{{ domain[item] }}"
    state: directory
    mode: "0755"
  loop: "{{ domain | list }}"
