#!/bin/bash

PLUGINDIR=$(dirname $0)
. $PLUGINDIR/utils.sh

set -o pipefail

LOG=$(/usr/bin/prosodyctl check | tail -n 1)
RETVAL=$?

if [ -z "$RETVAL" ]; then
    echo "ERROR: invalid output"
    exit $STATE_CRITICAL
fi

if [ $RETVAL -ne 0 ]; then
    echo "ERROR: Problems found"
    exit $STATE_CRITICAL
fi

echo "OK: $LOG"
exit $STATE_OK

