# Coturn
- name: Try to retrieve current shared TURN password
  shell: /usr/bin/grep -s ^static-auth-secret "/etc/coturn/turnserver.conf" | /usr/bin/sed 's/.*=\(.*\).*/\1/'
  register: turnpwd_current
  check_mode: false
  changed_when: false
  tags:
    - skip_ansible_lint

- name: Either use TURN password from host_vars, the current one or a new random one
  set_fact:
    turnpwd: "{{ turnserver.shared_password | default((turnpwd_current.stdout | length > 0) | ternary(turnpwd_current.stdout, lookup('password', '/dev/null chars=ascii_lowercase,ascii_uppercase,digits length=16'))) }}"

# Postgres
- name: Try to retrieve current Postgresql password
  shell: /usr/bin/awk '/^sql/,/}/' /etc/prosody/prosody.cfg.lua | /usr/bin/grep -s password | /usr/bin/sed 's/.*password\s*=\s*\"\(.*\)\".*/\1/'
  register: pgpwd_current
  check_mode: false
  changed_when: false
  tags:
    - skip_ansible_lint

- name: Either use Postgresql password from host_vars, the current one or a new random one
  set_fact:
    pgpwd: "{{ postgresql.password | default((pgpwd_current.stdout | length > 0) | ternary(pgpwd_current.stdout, lookup('password', '/dev/null chars=ascii_lowercase,ascii_uppercase,digits length=16'))) }}"


# Prosody
- name: Try to retrieve current shared upload passwords
  shell: /usr/bin/grep -s http_upload_external_secret "/etc/prosody/conf.d/{{ item.name }}.cfg.lua" | /usr/bin/sed 's/.*\"\(.*\)\".*/\1/'
  loop: "{{ prosody.xmpp_domains }}"
  register: uploadpwd_current
  check_mode: false
  changed_when: false
  tags:
    - skip_ansible_lint

- name: Either use the current shared upload password or create a new random one
  set_fact:
    uploadpwd: "{{ uploadpwd | default({}) | combine( { item.item.name: (item.stdout | length > 0 ) | ternary(item.stdout, lookup('password', '/dev/null chars=ascii_lowercase,ascii_uppercase,digits length=16')) } ) }}"
  loop: "{{ uploadpwd_current.results }}"


# NRPE
# FIXME
- name: Try to retrieve current test user passwords
  shell: /usr/bin/grep -s ^static-auth-secret "/etc/coturn/turnserverX.conf" | /usr/bin/sed 's/.*=\(.*\).*/\1/'
  loop: "{{ prosody.xmpp_domains }}"
  register: testuserpwd_current
  check_mode: false
  changed_when: false
  tags:
    - skip_ansible_lint

- name: Either use test user password from host_vars, use the current one or create a new random one
  set_fact:
    testuserpwd: "{{ testuserpwd | default({}) | combine( { item.item.name: (prosody.xmpp_domains | selectattr('name', 'equalto', item.item.name) | selectattr('testuser.password', 'defined') | map(attribute='testuser.password') | first ) | default((item.stdout | length > 0 ) | ternary(item.stdout, lookup('password', '/dev/null chars=ascii_lowercase,ascii_uppercase,digits length=16'))) } ) }}"
  loop: "{{ testuserpwd_current.results }}"

- name: DEBUG
  debug:
    msg: "ENDE: {{ testuserpwd }}"
