- name: Install Certbot
  zypper:
    name: "python3-certbot-apache"

# FIXME: Sollte von Certbot gemacht werden!
- name: Create directory for default TLS configuration for Apache2
  file:
    path: /etc/letsencrypt
    state: directory
    mode: "0755"

- name: Create default TLS configuration for Apache2
  copy:
    src: options-ssl-apache.conf
    dest: /etc/letsencrypt/options-ssl-apache.conf
    mode: "0644"

- name: Create certificates for XMPP components
  include_tasks: vhosts.yml
  loop: "{{ prosody.xmpp_domains | map(attribute='components') }}"
  loop_control:
    loop_var: domain

- name: Create directory for renewal hooks
  file:
    path: "/etc/letsencrypt/renewal-hooks/post/"
    state: directory
    mode: "0755"

- name: Add renewal hooks to certbot
  copy:
    src: "{{ item }}"
    dest: "/etc/letsencrypt/renewal-hooks/post/{{ item }}"
    mode: "0770"
  loop:
    - coturn.sh
    - apache2.sh
    - prosody.sh

- name: Add certbot cronjob
  cron:
    name: "Renew LetsEncrypt Certificates, check weekly. After renewal scripts in /etc/letsencrypt/renewal-hooks/post get executed to enable the new certs in Apache2, Coturn and Prosody"
    job: "/usr/bin/certbot renew"
    minute: "10"
    hour: "1"
    weekday: "0"
