- name: Check if certificates do already exist
  stat:
    path: /etc/letsencrypt/live/{{ item }}/cert.pem
  register: letsencrypt_cert_stat
  loop: "{{ domain | dict2items | map(attribute='value') + [ prosody.web_domain.name | default(inventory_hostname) ] }}"

- name: Stop Apache2 to allow certbot to generate a cert
  service:
    name: "apache2"
    state: stopped
  when: not ansible_check_mode and letsencrypt_cert_stat.results | selectattr('stat.exists','equalto', false) | list | count > 0
  notify: restart apache2
  register: apache2_service_result
  failed_when: "apache2_service_result is failed and 'Could not find the requested service' not in apache2_service_result.msg"

- name: Generate new certificate
  command: /snap/bin/certbot certonly --standalone --noninteractive --agree-tos --email {{ prosody.web_domain.admin_email }} -d {{ item }}
  args:
    creates: /etc/letsencrypt/live/{{ item }}/cert.pem
  loop: "{{ domain | dict2items | map(attribute='value') + [ prosody.web_domain.name | default(inventory_hostname) ] }}"

